# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonsai < Formula
  desc "Interactive TUI for safely pruning local git branches."
  homepage "https://github.com/nilBora/gonsai"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/nilBora/gonsai/releases/download/v0.1.0/gonsai_0.1.0_darwin_amd64.tar.gz"
    sha256 "2f10447ccdb0768e265c73a867178f870d2556a169e7e456ebdc86640596178a"

    define_method(:install) do
      bin.install "gonsai"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/nilBora/gonsai/releases/download/v0.1.0/gonsai_0.1.0_darwin_arm64.tar.gz"
    sha256 "09687b5f1402f77716a08449a51b599e077d3bf023e84fc60d46845faa9245b4"

    define_method(:install) do
      bin.install "gonsai"
    end
  end

  test do
    system "#{bin}/gonsai", "--version"
  end
end
